export default [
  {
    id: 1110,
    url: 'blog/featured-snippet/',
    lang: 'en',
    title: 'How to Optimize for Google Featured Snippets [Research]',
    preview: 'When the featured snippet was first introduced, it became something of a podium prize. Google, being Google, didn’t give us much in the way of how to earn a featured snippet, but SEOs, being SEOs, crunched the data to win the race anyway.',
    previewImage: 'article/how-to.webp',
    category: {
      name: 'SEO',
      slug: 'seo',
      lang: 'en',
    },
    isHot: 0,
    publishedAt: 1604401500,
    editedAt: 1604500020,
    background: 'orangeIllust'
  },
  {
    id: 29833,
    url: 'blog/content-strategy-for-ecommerce',
    lang: 'en',
    title: 'How to Create an Effective Content Strategy for Ecommerce',
    preview: 'To create ecommerce website content tailored to buyer needs, you need to understand your user‘s buyer persona and your audience. Plus, you have to create content that converts! Learn more about our ecommerce content tips and how you can create an ecommerce content strategy for your business by reading our guide.',
    previewImage: 'https://storage.googleapis.com/blog-rc/front/rc/blog/article/content-strategy-for-e-commerce.png',
    category: {
      name: 'SEO',
      slug: 'seo',
      lang: 'en',
    },
    isHot: 0,
    publishedAt: 1604401500,
    editedAt: 1604500020,
    background: 'purpleIllust'
  },
  {
    id: 29786,
    url: 'blog/seo-faq',
    lang: 'en',
    title: 'SEO FAQs and The 23 Most Asked Basic Questions About SEO',
    preview: 'If you‘re just starting out in SEO or are a business owner who is looking to improve the performance of their website and make it easier to find on the search engines, there‘s a very good chance that you have a lot of questions, and in this guide, we‘ve answered 23 of those that we most commonly hear asked.',
    previewImage: 'https://storage.googleapis.com/blog/front/rc/blog/article/SEO-FAQ-Most-Asked-Basic-Questions_big.png',
    category: {
      name: 'Advanced SEO',
      slug: 'seo/advanced-seo',
      lang: 'en',
    },
    isHot: 0,
    publishedAt: 1603372800,
    editedAt: 1603374002,
    background: 'blueIllust',
  },
  {
    id: 7036,
    url: 'blog/6-common-misconceptions-about-seo-that-can-hurt-your-digital-marketing',
    lang: 'en',
    title: '6 Common Misconceptions About SEO that Can Hurt Your Digital Marketing',
    preview: 'The importance of SEO is hardly a secret in 2017. But, even though business owners may know how vital it is to optimize their sites, they are often guided by SEO misconceptions. This post busts all of the most common myths and misconceptions about SEO.',
    previewImage: 'https://storage.googleapis.com/blog/front/rc/blog/article/seo-misconceptions-022817.jpg',
    category: {
      name: 'Advanced SEO',
      slug: 'seo/advanced-seo',
      lang: 'en',
    },
    isHot: 0,
    publishedAt: 1488301200,
    editedAt: 1590526962,
    background: 'orangeIllust',
  },
  {
    id: 101010,
    url: 'blog/most-visited-websites/',
    lang: 'en',
    title: 'Top 100: The Most Visited Websites in the US [2020 Top Websites Edition]',
    preview: 'This post uncovers the top 100 most visited websites in the US, deep-diving into a few industries - Media, Retail, and Streaming Services - that show the biggest position changes.',
    previewImage: 'https://storage.googleapis.com/blog/front/rc/blog/article/top-100.jpg',
    category: {
      name: 'Marketing',
      slug: 'marketing',
      lang: 'en',
    },
    isHot: 0,
    publishedAt: 1604401500,
    editedAt: 1604500020,
    background: 'orangeIllust',
  },
  {
    id: 434,
    url: 'blog/google-revamps-pagespeed-extension-user-friendly-tool',
    lang: 'en',
    title: 'Google Revamps the PageSpeed Extension Into a User-Friendly Tool',
    preview: 'For years now, Google has offered webmasters the ability to test pageload speeds via browser extensions and an API. For non-technical SEOs, the PageSpeed Insights extension for Chrome and Firefox has been helpful in determining on-page fixes. But anyone who’s used the extension before can tell you the analysis is difficult to put to good use because of how the extension is set up.Thankfully, Google took the hint. The PageSpeed Insights tool now makes it all the easier to pinpoint loading issues on your site and fix them. Or, at least so you can tell your favorite web developer what needs to be fixed to improve site performance.',
    previewImage: '',
    category: null,
    isHot: 0,
    publishedAt: 1385050728,
    editedAt: 1495709941,
  },
  {
    id: 436,
    url: 'blog/seos-around-world-hummingbird-qa-mike-van-der-heijden',
    lang: 'en',
    title: 'SEOs Around the World: Hummingbird Q&A with Mike van der Heijden',
    preview: 'From the US to Australia!Mike van der Heijden, SEO Director for search agency Atomic Search talks about Hummingbird. Get ready to know more about the new algorithm.&nbsp;Spoiler alert: be prepared to work hard on changes!&nbsp;&nbsp;&nbsp;&nbsp;',
    previewImage: 'https://storage.googleapis.com/blog/front/rc/blog/article/mike-van-der-heijden-276x415.jpg',
    category: null,
    isHot: 0,
    publishedAt: 1385643443,
    editedAt: 1464525503
  },
];
