export default [
  {
    id: 1,
    title: 'The Ultimate Guide to Google Search Operators and Google Search Commands',
    previewImage: 'https://static.example.com/blog/uploads/media/ec/23/ec23597b206c67f2845e3cc9f7ac7221/go-to-market-strategy-checklist-sm-1.svg',
    background: 'blueIllust',
    url: 'blog/what-is-seo/',
    timeToRead: 16,
  },
  {
    id: 2,
    title: 'The Ultimate Guide to Google Search Operators and Google Search Commands',
    previewImage: 'https://static.example.com/blog/uploads/media/a6/55/a655f41ab8a81c760c3db3784d3f7330/perform-a-content-audit.svg',
    url: 'blog/what-is-seo/',
    timeToRead: 16,
    background: 'yellowIllust',
  },
  {
    id: 3,
    title: 'The Top 10 Search Engines Today',
    previewImage: 'https://static.example.com/blog/uploads/media/d6/6c/d66cd227c24cf1fb9ca43417e3cfda7f/improve-seo.svg',
    url: 'blog/what-is-seo/',
    timeToRead: 14,
    background: 'greenIllust',
  },
  {
    id: 4,
    title: 'The Complete Guide to (Effective) Customer Analysis',
    previewImage: 'https://static.example.com/blog/uploads/media/d0/e1/d0e16a59f09f064f66f68c1bfa80e904/market-assessment.svg',
    url: 'blog/what-is-seo/',
    timeToRead: 13,
    background: 'orangePaleIllust',
  },
  {
    id: 5,
    title: 'How to Analyze Competitor Website Traffic with .Trends',
    previewImage: 'https://static.example.com/blog/uploads/media/01/dd/01dd71a0e8acd1da9a9ac671e9d2566f/how-to-choose-long-tail-keywords.svg',
    url: 'blog/what-is-seo/',
    timeToRead: 12,
    background: 'orangePaleIllust',
  },
  {
    id: 6,
    title: 'SEO Split-Test Result: Does Emphasizing an H1 Impact Organic Traffic?',
    previewImage: 'https://static.example.com/blog/uploads/media/f3/f9/f3f95a2b51ad1d2536c4de81b1880edf/what-is-seo.svg',
    url: 'blog/what-is-seo/',
    timeToRead: 16,
    background: 'yellowIllust',
  },
  {
    id: 7,
    title: '12 Essential SEO Tips for Beginners to Boost Traffic',
    previewImage: 'https://static.example.com/blog/uploads/media/18/ff/18fff960ff67c9db12b43013022a1a68/learning-technical-seo.svg',
    url: 'blog/what-is-seo/',
    timeToRead: 10,
    background: 'greenGrassIllust',

  },
  {
    id: 8,
    title: 'SEO Split-Test Result: Does Emphasizing an H1 Impact Organic Traffic?',
    previewImage: 'https://static.example.com/blog/uploads/media/9a/90/9a901e4780fc4e441faa8ee8deb71e48/splitsignal-case-study-18-sm.svg',
    url: 'blog/what-is-seo/',
    timeToRead: 14,
    background: 'orangePaleIllust',
  },
  {
    id: 9,
    title: 'The Ultimate Guide to Google Search Operators and Google Search Commands',
    previewImage: 'https://static.example.com/blog/uploads/media/11/52/11525d5a85322a3b163cfbd9684c9768/best-competitive-intelligence-tools-for-market-research.svg',
    url: 'blog/what-is-seo/',
    timeToRead: 16,
    background: 'orangeIllust',
  },
  {
    id: 10,
    title: 'What Is SEO? The 2022 Guide to Search Engine Optimization',
    previewImage: 'https://static.example.com/blog/uploads/media/a6/55/a655f41ab8a81c760c3db3784d3f7330/perform-a-content-audit.svg',
    url: 'blog/what-is-seo/',
    timeToRead: 12,
    background: 'yellowIllust',
  },
  {
    id: 11,
    title: 'The Ultimate Guide to Google Search Operators and Google Search Commands',
    previewImage: 'https://static.example.com/blog/uploads/media/ec/23/ec23597b206c67f2845e3cc9f7ac7221/go-to-market-strategy-checklist-sm-1.svg',
    background: 'blueIllust',
    url: 'blog/what-is-seo/',
    timeToRead: 16,
  },
  {
    id: 12,
    title: 'The Ultimate Guide to Google Search Operators and Google Search Commands',
    previewImage: 'https://static.example.com/blog/uploads/media/a6/55/a655f41ab8a81c760c3db3784d3f7330/perform-a-content-audit.svg',
    url: 'blog/what-is-seo/',
    timeToRead: 16,
    background: 'yellowIllust',
  },
  {
    id: 13,
    title: 'The Top 10 Search Engines Today',
    previewImage: 'https://static.example.com/blog/uploads/media/d6/6c/d66cd227c24cf1fb9ca43417e3cfda7f/improve-seo.svg',
    url: 'blog/what-is-seo/',
    timeToRead: 14,
    background: 'greenIllust',
  },
  {
    id: 14,
    title: 'The Complete Guide to (Effective) Customer Analysis',
    previewImage: 'https://static.example.com/blog/uploads/media/d0/e1/d0e16a59f09f064f66f68c1bfa80e904/market-assessment.svg',
    url: 'blog/what-is-seo/',
    timeToRead: 13,
    background: 'orangePaleIllust',
  },
  {
    id: 15,
    title: 'How to Analyze Competitor Website Traffic with .Trends',
    previewImage: 'https://static.example.com/blog/uploads/media/01/dd/01dd71a0e8acd1da9a9ac671e9d2566f/how-to-choose-long-tail-keywords.svg',
    url: 'blog/what-is-seo/',
    timeToRead: 12,
    background: 'orangePaleIllust',
  },
  {
    id: 16,
    title: 'SEO Split-Test Result: Does Emphasizing an H1 Impact Organic Traffic?',
    previewImage: 'https://static.example.com/blog/uploads/media/f3/f9/f3f95a2b51ad1d2536c4de81b1880edf/what-is-seo.svg',
    url: 'blog/what-is-seo/',
    timeToRead: 16,
    background: 'yellowIllust',
  },
  {
    id: 17,
    title: '12 Essential SEO Tips for Beginners to Boost Traffic',
    previewImage: 'https://static.example.com/blog/uploads/media/18/ff/18fff960ff67c9db12b43013022a1a68/learning-technical-seo.svg',
    url: 'blog/what-is-seo/',
    timeToRead: 10,
    background: 'greenGrassIllust',

  },
  {
    id: 18,
    title: 'SEO Split-Test Result: Does Emphasizing an H1 Impact Organic Traffic?',
    previewImage: 'https://static.example.com/blog/uploads/media/9a/90/9a901e4780fc4e441faa8ee8deb71e48/splitsignal-case-study-18-sm.svg',
    url: 'blog/what-is-seo/',
    timeToRead: 14,
    background: 'orangePaleIllust',
  },
  {
    id: 19,
    title: 'The Ultimate Guide to Google Search Operators and Google Search Commands',
    previewImage: 'https://static.example.com/blog/uploads/media/11/52/11525d5a85322a3b163cfbd9684c9768/best-competitive-intelligence-tools-for-market-research.svg',
    url: 'blog/what-is-seo/',
    timeToRead: 16,
    background: 'orangeIllust',
  },
  {
    id: 20,
    title: 'What Is SEO? The 2022 Guide to Search Engine Optimization',
    previewImage: 'https://static.example.com/blog/uploads/media/a6/55/a655f41ab8a81c760c3db3784d3f7330/perform-a-content-audit.svg',
    url: 'blog/what-is-seo/',
    timeToRead: 12,
    background: 'yellowIllust',
  },
  {
    id: 21,
    title: 'The Ultimate Guide to Google Search Operators and Google Search Commands',
    previewImage: 'https://static.example.com/blog/uploads/media/ec/23/ec23597b206c67f2845e3cc9f7ac7221/go-to-market-strategy-checklist-sm-1.svg',
    background: 'blueIllust',
    url: 'blog/what-is-seo/',
    timeToRead: 16,
  },
  {
    id: 22,
    title: 'The Ultimate Guide to Google Search Operators and Google Search Commands',
    previewImage: 'https://static.example.com/blog/uploads/media/a6/55/a655f41ab8a81c760c3db3784d3f7330/perform-a-content-audit.svg',
    url: 'blog/what-is-seo/',
    timeToRead: 16,
    background: 'yellowIllust',
  },
  {
    id: 23,
    title: 'The Top 10 Search Engines Today',
    previewImage: 'https://static.example.com/blog/uploads/media/d6/6c/d66cd227c24cf1fb9ca43417e3cfda7f/improve-seo.svg',
    url: 'blog/what-is-seo/',
    timeToRead: 14,
    background: 'greenIllust',
  },
  {
    id: 24,
    title: 'The Complete Guide to (Effective) Customer Analysis',
    previewImage: 'https://static.example.com/blog/uploads/media/d0/e1/d0e16a59f09f064f66f68c1bfa80e904/market-assessment.svg',
    url: 'blog/what-is-seo/',
    timeToRead: 13,
    background: 'orangePaleIllust',
  },
  {
    id: 25,
    title: 'How to Analyze Competitor Website Traffic with .Trends',
    previewImage: 'https://static.example.com/blog/uploads/media/01/dd/01dd71a0e8acd1da9a9ac671e9d2566f/how-to-choose-long-tail-keywords.svg',
    url: 'blog/what-is-seo/',
    timeToRead: 12,
    background: 'orangePaleIllust',
  },
  {
    id: 26,
    title: 'SEO Split-Test Result: Does Emphasizing an H1 Impact Organic Traffic?',
    previewImage: 'https://static.example.com/blog/uploads/media/f3/f9/f3f95a2b51ad1d2536c4de81b1880edf/what-is-seo.svg',
    url: 'blog/what-is-seo/',
    timeToRead: 16,
    background: 'yellowIllust',
  },
  {
    id: 27,
    title: '12 Essential SEO Tips for Beginners to Boost Traffic',
    previewImage: 'https://static.example.com/blog/uploads/media/18/ff/18fff960ff67c9db12b43013022a1a68/learning-technical-seo.svg',
    url: 'blog/what-is-seo/',
    timeToRead: 10,
    background: 'greenGrassIllust',

  },
  {
    id: 28,
    title: 'SEO Split-Test Result: Does Emphasizing an H1 Impact Organic Traffic?',
    previewImage: 'https://static.example.com/blog/uploads/media/9a/90/9a901e4780fc4e441faa8ee8deb71e48/splitsignal-case-study-18-sm.svg',
    url: 'blog/what-is-seo/',
    timeToRead: 14,
    background: 'orangePaleIllust',
  },
  {
    id: 29,
    title: 'The Ultimate Guide to Google Search Operators and Google Search Commands',
    previewImage: 'https://static.example.com/blog/uploads/media/11/52/11525d5a85322a3b163cfbd9684c9768/best-competitive-intelligence-tools-for-market-research.svg',
    url: 'blog/what-is-seo/',
    timeToRead: 16,
    background: 'orangeIllust',
  },
  {
    id: 30,
    title: 'What Is SEO? The 2022 Guide to Search Engine Optimization',
    previewImage: 'https://static.example.com/blog/uploads/media/a6/55/a655f41ab8a81c760c3db3784d3f7330/perform-a-content-audit.svg',
    url: 'blog/what-is-seo/',
    timeToRead: 12,
    background: 'yellowIllust',
  },
  {
    id: 31,
    title: 'The Ultimate Guide to Google Search Operators and Google Search Commands',
    previewImage: 'https://static.example.com/blog/uploads/media/ec/23/ec23597b206c67f2845e3cc9f7ac7221/go-to-market-strategy-checklist-sm-1.svg',
    background: 'blueIllust',
    url: 'blog/what-is-seo/',
    timeToRead: 16,
  },
  {
    id: 32,
    title: 'The Ultimate Guide to Google Search Operators and Google Search Commands',
    previewImage: 'https://static.example.com/blog/uploads/media/a6/55/a655f41ab8a81c760c3db3784d3f7330/perform-a-content-audit.svg',
    url: 'blog/what-is-seo/',
    timeToRead: 16,
    background: 'yellowIllust',
  },
  {
    id: 33,
    title: 'The Top 10 Search Engines Today',
    previewImage: 'https://static.example.com/blog/uploads/media/d6/6c/d66cd227c24cf1fb9ca43417e3cfda7f/improve-seo.svg',
    url: 'blog/what-is-seo/',
    timeToRead: 14,
    background: 'greenIllust',
  },
  {
    id: 34,
    title: 'The Complete Guide to (Effective) Customer Analysis',
    previewImage: 'https://static.example.com/blog/uploads/media/d0/e1/d0e16a59f09f064f66f68c1bfa80e904/market-assessment.svg',
    url: 'blog/what-is-seo/',
    timeToRead: 13,
    background: 'orangePaleIllust',
  },
  {
    id: 35,
    title: 'How to Analyze Competitor Website Traffic with .Trends',
    previewImage: 'https://static.example.com/blog/uploads/media/01/dd/01dd71a0e8acd1da9a9ac671e9d2566f/how-to-choose-long-tail-keywords.svg',
    url: 'blog/what-is-seo/',
    timeToRead: 12,
    background: 'orangePaleIllust',
  },
  {
    id: 36,
    title: 'SEO Split-Test Result: Does Emphasizing an H1 Impact Organic Traffic?',
    previewImage: 'https://static.example.com/blog/uploads/media/f3/f9/f3f95a2b51ad1d2536c4de81b1880edf/what-is-seo.svg',
    url: 'blog/what-is-seo/',
    timeToRead: 16,
    background: 'yellowIllust',
  },
  {
    id: 37,
    title: '12 Essential SEO Tips for Beginners to Boost Traffic',
    previewImage: 'https://static.example.com/blog/uploads/media/18/ff/18fff960ff67c9db12b43013022a1a68/learning-technical-seo.svg',
    url: 'blog/what-is-seo/',
    timeToRead: 10,
    background: 'greenGrassIllust',

  },
  {
    id: 38,
    title: 'SEO Split-Test Result: Does Emphasizing an H1 Impact Organic Traffic?',
    previewImage: 'https://static.example.com/blog/uploads/media/9a/90/9a901e4780fc4e441faa8ee8deb71e48/splitsignal-case-study-18-sm.svg',
    url: 'blog/what-is-seo/',
    timeToRead: 14,
    background: 'orangePaleIllust',
  },
  {
    id: 39,
    title: 'The Ultimate Guide to Google Search Operators and Google Search Commands',
    previewImage: 'https://static.example.com/blog/uploads/media/11/52/11525d5a85322a3b163cfbd9684c9768/best-competitive-intelligence-tools-for-market-research.svg',
    url: 'blog/what-is-seo/',
    timeToRead: 16,
    background: 'orangeIllust',
  },
  {
    id: 40,
    title: 'What Is SEO? The 2022 Guide to Search Engine Optimization',
    previewImage: 'https://static.example.com/blog/uploads/media/a6/55/a655f41ab8a81c760c3db3784d3f7330/perform-a-content-audit.svg',
    url: 'blog/what-is-seo/',
    timeToRead: 12,
    background: 'yellowIllust',
  },
];
