import authors from './authors';
import categories from './categories';

export default [
  {
    id: '1',
    title: 'The Ultimate Guide to Google Search Operators and Google Search Commands',
    preview:
      'In this guide, we’ll delve deep into the basics of search operators and search commands, helping you understand how to wield these powerful tools effectively and move on to advanced commands and operators.',
    category: categories[5],
    isHot: false,
    timeToRead: 15,
    previewImage: 'https://storage.googleapis.com/blog-rc/testing/article-list/1.jpg',
    altPreviewImage: 'Article Image',
    author: authors[0],
    url: 'white-hat-seo',
    publishedAt: 1597908972,
    share: 10,
  },
  {
    id: '2',
    title: 'Some article text with captions and tool words and third party keys and other stuff',
    preview:
      'In this guide, we’ll delve deep into the basics of search operators and search commands, helping you understand how to wield these powerful tools effectively and move on to advanced commands and operators.',
    category: categories[0],
    isHot: true,
    timeToRead: 16,
    previewImage: 'https://storage.googleapis.com/blog/testing/article-list/3.jpg',
    altPreviewImage: 'Article Image',
    author: authors[1],
    url: 'how-to-rank-a-youtube-video',
    publishedAt: 1597908972,
    share: 10,
  },
  {
    id: '3',
    title: 'A article text with captions and tool words and third party keys and other stuff',
    preview:
      'In this guide, we’ll delve deep into the basics of search operators and search commands, helping you understand how to wield these powerful tools effectively and move on to advanced commands and operators.',
    category: categories[0],
    isHot: false,
    timeToRead: 2,
    previewImage: 'https://storage.googleapis.com/blog/testing/article-list/4.jpg',
    altPreviewImage: 'Article Image',
    author: authors[0],
    url: 'improve-seo',
    publishedAt: 1597908972,
    share: 10,
  },
  {
    id: '4',
    title: 'A article text with captions and tool words and third party keys and other stuff',
    preview:
      'In this guide, we’ll delve deep into the basics of search operators and search commands, helping you understand how to wield these powerful tools effectively and move on to advanced commands and operators.',
    category: categories[4],
    isHot: false,
    timeToRead: 44,
    previewImage: 'https://storage.googleapis.com/blog/testing/article-list/2.jpg',
    altPreviewImage: 'Article Image',
    author: authors[1],
    url: 'improve-seo',
    publishedAt: 1597908972,
    share: 10,
  },
  {
    id: '5',
    title: 'A article text with captions and tool words and third party keys and other stuff',
    preview:
      'In this guide, we’ll delve deep into the basics of search operators and search commands, helping you understand how to wield these powerful tools effectively and move on to advanced commands and operators.',
    category: categories[3],
    isHot: false,
    timeToRead: 5,
    previewImage: 'https://storage.googleapis.com/blog/testing/article-list/3.jpg',
    altPreviewImage: 'Article Image',
    author: authors[0],
    url: 'improve-seo',
    publishedAt: 1597908972,
    share: 10,
  },
];
